baseURL: https://www.bogmat.xyz/
languageCode: en-GB
title: Crane & timber bog mats
theme: starter
pluralizeListTitles: false
copyright: This work is dual-licensed under MIT & GPL v3
paginate: 2
summaryLength: 13
author:
  name: Jake Rayson
  email: hello@growdigital.org
taxonomies:
  tag: tags
params:
  description: Our bog mats are great!
  publisher: Bogmats
  publisherLogo: assets/img/logo.png
  publisherLogoWidth: 220
  publisherLogoHeight: 220
  twitter: bogmat1
  facebook: IndiegoHugo
  linkedin: indiegohugo
  email: bogmat@protonmail.com
  googleplus: 112354208488638707199
  fbapp_id: 206433049934562
  tel: "+447398474064"
